name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'
        
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libgl1-mesa-dev xorg-dev
        
    - name: Get dependencies
      run: go mod download
      
    - name: Verify dependencies
      run: go mod verify
      
    - name: Build
      run: go build -v ./...
      
    - name: Test version injection
      run: |
        # Test that we can build with version injection
        go build -ldflags "-X github.com/sfkleach/roll/internal/info.Version=test-ci" -o roll-test .
        ./roll-test --version
        rm roll-test
      
    - name: Run tests
      run: go test -v ./...
      
    - name: Run tests with race detector
      run: go test -race -v ./internal/...

  lint:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'
        
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: latest
